### ISSUE TITLE
ionic lab raise error

### ISSUE THREAD

**Issue by neyamii** [driftyco/ionic-lab-issues#109]
Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (57)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.5.0
    at module.exports (R:\z_test\f-ion\f-ion\f-ion\node_modules\node-sass\lib\binding.js:13:13)
    at Object.<anonymous> (R:\z_test\f-ion\f-ion\f-ion\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (R:\z_test\f-ion\f-ion\f-ion\node_modules\@ionic\app-scripts\dist\sass.js:11:19)

**Comment by neyamii** [comment]
windows 10
ionic 3.20
node 8.10
npm 5.8
