### ISSUE TITLE
ionic lab always showing offline

### ISSUE THREAD

**Issue by ray86** [driftyco/ionic-lab-issues#76]
ionic lab always showing offline even though am connected to the internet, creating a new app keeps loading forever  and i keep gettting this error:
fail to opensync Error: ENOENT: no such file or directory, open 'C:\Users\SMARTKON1\AppData\Local\Temp;c:\ffmpeg\bin\ionic-lab-logfile.log'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync](ATOM_SHELL_ASAR.js:137:20)
    at Object.init (file:///C:/Users/SMARTKON1/AppData/Local/IonicLab/app-1.0.0/resources/app.asar/js/services/logging.js:42:22)
    at file:///C:/Users/SMARTKON1/AppData/Local/IonicLab/app-1.0.0/resources/app.asar/js/app.js:8:22
    at Array.<anonymous> (file:///C:/Users/SMARTKON1/AppData/Local/IonicLab/app-1.0.0/resources/app.asar/lib/ionic/release/js/ionic.bundle.js:48811:19)
    at onPlatformReady (file:///C:/Users/SMARTKON1/AppData/Local/IonicLab/app-1.0.0/resources/app.asar/lib/ionic/release/js/ionic.bundle.js:2447:24)
    at onWindowLoad (file:///C:/Users/SMARTKON1/AppData/Local/IonicLab/app-1.0.0/resources/app.asar/lib/ionic/release/js/ionic.bundle.js:2428:7)

**Comment by ufhy** [comment]
same to me

**Comment by DrSensor** [comment]
same here. and i'm using Linux

**Comment by jxxyxb** [comment]
me too
